import type { Metadata } from "next";
import '@mantine/core/styles.css';

import { MantineProvider } from '@mantine/core';
import { McMurtryTheme } from "./theme"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={McMurtryTheme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
